package selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class DefaultSuiteTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    // @After
    // public void tearDown() {
    //     driver.quit();
    // }

    @Test
    public void test1() {
        driver.get("https://blog.csdn.net/x625552409");
        WebElement e = driver.findElement(By.cssSelector(".toolbar-btn-login"));
        System.out.println();
        js.executeScript("window.hasEle=(seletor)=>(!!document.querySelector(seletor))");
        vars.put("has", js.executeScript("return hasEle(\'.toolbar-btn-login\')"));
        System.out.println(vars.get("has").toString());
    }
}
