package selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class Test1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void test1() {
        driver.get("https://www.dogedoge.com/");
        driver.manage().window().setSize(new Dimension(1261, 785));
        driver.findElement(By.id("search_form_input_homepage")).click();
        driver.findElement(By.id("search_form_input_homepage")).click();
        driver.findElement(By.id("search_form_input_homepage")).sendKeys("今天应该怎么玩呢");
        driver.findElement(By.id("search_form_input_homepage")).sendKeys(Keys.ENTER);
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector("#r-101\\.28 em:nth-child(2)")).click();
        vars.put("第二个连接", waitForWindow(2000));
        driver.switchTo().window(vars.get("第二个连接").toString());
    }
}
